# Note: This file was generated by Cursor AI.
# The purpose of this file is to demonstrate how to use the Pydantic AI agent as an API.

import os
import uuid
from contextlib import asynccontextmanager
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from pydantic_ai import Agent
from pydantic_ai.capabilities import WebSearch
from pydantic_ai.mcp import MCPToolset
from pydantic_ai.messages import ModelMessage
from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.openai import OpenAIProvider
from fastmcp.client.transports import StdioTransport
import logfire
import uvicorn

load_dotenv()

logfire.configure()
logfire.instrument_pydantic_ai()

model = OpenAIChatModel(
    model_name=os.environ.get("MODEL_NAME"),
    provider=OpenAIProvider(
        base_url=os.environ.get("BASE_URL"),
        api_key=os.environ.get("API_KEY"),
    ),
)

workspace = os.environ.get("SAFE_FILE_SYSTEM_FOLDER")
if not workspace:
    raise RuntimeError("SAFE_FILE_SYSTEM_FOLDER must be set in .env")

Path(workspace).mkdir(parents=True, exist_ok=True)

playwright_mcp = MCPToolset(
    StdioTransport(
        command="npx",
        args=["-y", "@playwright/mcp@latest", "--headless"],
    )
).prefixed("browser")

file_system_mcp = MCPToolset(
    StdioTransport(
        command="npx",
        args=["-y", "@modelcontextprotocol/server-filesystem", workspace],
    )
).prefixed("fs")

agent = Agent(
    model,
    instructions="""You are a helpful assistant.

Use web search when the user asks about current information or explicitly asks you to search.
Use it no more than twice for one user request. After receiving useful search results, answer
the user instead of searching again. When using search, always include the source URLs.

Use Playwright (browser MCP) when the user asks you to open, browse, or interact with a web page.

Use the filesystem MCP when reading, writing, or editing files. Stay inside the allowed workspace
folder. If a file has a `.md` extension, format it as markdown.""",
    capabilities=[WebSearch(local="duckduckgo")],
    toolsets=[playwright_mcp, file_system_mcp],
)

# In-memory chat history keyed by session_id. Fine for a local tutorial; restarting
# the server clears it.
sessions: dict[str, list[ModelMessage]] = {}


@asynccontextmanager
async def lifespan(_app: FastAPI):
    # Keep stdio MCP subprocesses (Playwright + filesystem) running for the
    # lifetime of the API instead of starting them on every request.
    async with agent:
        yield


app = FastAPI(
    title="Pydantic AI assistant API",
    description="Lesson 10: web search, Playwright MCP, filesystem MCP, served over FastAPI.",
    lifespan=lifespan,
)
logfire.instrument_fastapi(app)


class ChatRequest(BaseModel):
    prompt: str = Field(min_length=1)
    session_id: str | None = None


class ChatResponse(BaseModel):
    output: str
    session_id: str


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest) -> ChatResponse:
    session_id = request.session_id or str(uuid.uuid4())
    message_history = sessions.get(session_id, [])

    try:
        result = await agent.run(
            request.prompt,
            message_history=message_history,
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    sessions[session_id] = result.all_messages()
    return ChatResponse(output=str(result.output), session_id=session_id)


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)
